# Generated by Django 4.2.23 on 2025-08-26 11:40

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('filetype', models.TextField(blank=True, null=True)),
                ('int_observation', models.IntegerField(blank=True, null=True)),
                ('fullness', models.FloatField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('staid', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('staname', models.TextField(blank=True, null=True)),
                ('longstaname', models.TextField(blank=True, null=True)),
                ('network', models.TextField(blank=True, null=True)),
                ('agency', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('receiver', models.TextField(blank=True, null=True)),
                ('recvers', models.TextField(blank=True, null=True)),
                ('recnum', models.TextField(blank=True, null=True)),
                ('antenna', models.TextField(blank=True, null=True)),
                ('antnum', models.TextField(blank=True, null=True)),
                ('deltan', models.FloatField(blank=True, null=True)),
                ('deltae', models.FloatField(blank=True, null=True)),
                ('deltah', models.FloatField(blank=True, null=True)),
                ('startdate', models.TextField(blank=True, null=True)),
                ('enddate', models.TextField(blank=True, null=True)),
                ('sta_daterange', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': False,
            },
        ),
    ]
